<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // Pays africains (focus principal)
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV'],
            ['name' => 'Sénégal', 'code' => 'SEN'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'Cameroun', 'code' => 'CMR'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'République démocratique du Congo', 'code' => 'COD'],
            ['name' => 'Tchad', 'code' => 'TCD'],
            ['name' => 'Centrafrique', 'code' => 'CAF'],
            ['name' => 'Guinée', 'code' => 'GIN'],
            ['name' => 'Guinée-Bissau', 'code' => 'GNB'],
            ['name' => 'Sierra Leone', 'code' => 'SLE'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Togo', 'code' => 'TGO'],
            ['name' => 'Bénin', 'code' => 'BEN'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Maroc', 'code' => 'MAR'],
            ['name' => 'Algérie', 'code' => 'DZA'],
            ['name' => 'Tunisie', 'code' => 'TUN'],
            ['name' => 'Libye', 'code' => 'LBY'],
            ['name' => 'Égypte', 'code' => 'EGY'],
            ['name' => 'Soudan', 'code' => 'SDN'],
            ['name' => 'Éthiopie', 'code' => 'ETH'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Tanzanie', 'code' => 'TZA'],
            ['name' => 'Ouganda', 'code' => 'UGA'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Madagascar', 'code' => 'MDG'],
            ['name' => 'Maurice', 'code' => 'MUS'],
            ['name' => 'Seychelles', 'code' => 'SYC'],
            ['name' => 'Comores', 'code' => 'COM'],
            ['name' => 'Djibouti', 'code' => 'DJI'],
            ['name' => 'Somalie', 'code' => 'SOM'],
            ['name' => 'Afrique du Sud', 'code' => 'ZAF'],
            ['name' => 'Namibie', 'code' => 'NAM'],
            ['name' => 'Botswana', 'code' => 'BWA'],
            ['name' => 'Zimbabwe', 'code' => 'ZWE'],
            ['name' => 'Zambie', 'code' => 'ZMB'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Mozambique', 'code' => 'MOZ'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Cabo Verde', 'code' => 'CPV'],
            ['name' => 'São Tomé-et-Príncipe', 'code' => 'STP'],
            ['name' => 'Guinée équatoriale', 'code' => 'GNQ'],
            ['name' => 'Mauritanie', 'code' => 'MRT'],
            ['name' => 'Gambie', 'code' => 'GMB'],

            // Grands pays européens
            ['name' => 'France', 'code' => 'FRA'],
            ['name' => 'Allemagne', 'code' => 'DEU'],
            ['name' => 'Italie', 'code' => 'ITA'],
            ['name' => 'Espagne', 'code' => 'ESP'],
            ['name' => 'Portugal', 'code' => 'PRT'],
            ['name' => 'Royaume-Uni', 'code' => 'GBR'],
            ['name' => 'Belgique', 'code' => 'BEL'],
            ['name' => 'Pays-Bas', 'code' => 'NLD'],
            ['name' => 'Suisse', 'code' => 'CHE'],
            ['name' => 'Autriche', 'code' => 'AUT'],
            ['name' => 'Suède', 'code' => 'SWE'],
            ['name' => 'Norvège', 'code' => 'NOR'],
            ['name' => 'Danemark', 'code' => 'DNK'],
            ['name' => 'Finlande', 'code' => 'FIN'],
            ['name' => 'Pologne', 'code' => 'POL'],
            ['name' => 'République tchèque', 'code' => 'CZE'],
            ['name' => 'Hongrie', 'code' => 'HUN'],
            ['name' => 'Roumanie', 'code' => 'ROU'],
            ['name' => 'Bulgarie', 'code' => 'BGR'],
            ['name' => 'Grèce', 'code' => 'GRC'],
            ['name' => 'Croatie', 'code' => 'HRV'],
            ['name' => 'Slovénie', 'code' => 'SVN'],
            ['name' => 'Slovaquie', 'code' => 'SVK'],
            ['name' => 'Lituanie', 'code' => 'LTU'],
            ['name' => 'Lettonie', 'code' => 'LVA'],
            ['name' => 'Estonie', 'code' => 'EST'],
            ['name' => 'Irlande', 'code' => 'IRL'],
            ['name' => 'Islande', 'code' => 'ISL'],
            ['name' => 'Luxembourg', 'code' => 'LUX'],
            ['name' => 'Malte', 'code' => 'MLT'],
            ['name' => 'Chypre', 'code' => 'CYP'],

            // États-Unis et Canada
            ['name' => 'États-Unis', 'code' => 'USA'],
            ['name' => 'Canada', 'code' => 'CAN'],

            // Grands pays d'Asie
            ['name' => 'Chine', 'code' => 'CHN'],
            ['name' => 'Japon', 'code' => 'JPN'],
            ['name' => 'Corée du Sud', 'code' => 'KOR'],
            ['name' => 'Inde', 'code' => 'IND'],
            ['name' => 'Thaïlande', 'code' => 'THA'],
            ['name' => 'Vietnam', 'code' => 'VNM'],
            ['name' => 'Singapour', 'code' => 'SGP'],
            ['name' => 'Malaisie', 'code' => 'MYS'],
            ['name' => 'Indonésie', 'code' => 'IDN'],
            ['name' => 'Philippines', 'code' => 'PHL'],
            ['name' => 'Taiwan', 'code' => 'TWN'],
            ['name' => 'Hong Kong', 'code' => 'HKG'],
            ['name' => 'Macao', 'code' => 'MAC'],
            ['name' => 'Brunei', 'code' => 'BRN'],
            ['name' => 'Cambodge', 'code' => 'KHM'],
            ['name' => 'Laos', 'code' => 'LAO'],
            ['name' => 'Myanmar', 'code' => 'MMR'],
            ['name' => 'Bangladesh', 'code' => 'BGD'],
            ['name' => 'Pakistan', 'code' => 'PAK'],
            ['name' => 'Sri Lanka', 'code' => 'LKA'],
            ['name' => 'Maldives', 'code' => 'MDV'],
            ['name' => 'Népal', 'code' => 'NPL'],
            ['name' => 'Bhoutan', 'code' => 'BTN'],
            ['name' => 'Mongolie', 'code' => 'MNG'],
            ['name' => 'Kazakhstan', 'code' => 'KAZ'],
            ['name' => 'Ouzbékistan', 'code' => 'UZB'],
            ['name' => 'Kirghizistan', 'code' => 'KGZ'],
            ['name' => 'Tadjikistan', 'code' => 'TJK'],
            ['name' => 'Turkménistan', 'code' => 'TKM'],
            ['name' => 'Afghanistan', 'code' => 'AFG'],
            ['name' => 'Iran', 'code' => 'IRN'],
            ['name' => 'Irak', 'code' => 'IRQ'],
            ['name' => 'Arabie saoudite', 'code' => 'SAU'],
            ['name' => 'Émirats arabes unis', 'code' => 'ARE'],
            ['name' => 'Qatar', 'code' => 'QAT'],
            ['name' => 'Koweït', 'code' => 'KWT'],
            ['name' => 'Bahreïn', 'code' => 'BHR'],
            ['name' => 'Oman', 'code' => 'OMN'],
            ['name' => 'Yémen', 'code' => 'YEM'],
            ['name' => 'Jordanie', 'code' => 'JOR'],
            ['name' => 'Liban', 'code' => 'LBN'],
            ['name' => 'Syrie', 'code' => 'SYR'],
            ['name' => 'Israël', 'code' => 'ISR'],
            ['name' => 'Palestine', 'code' => 'PSE'],
            ['name' => 'Turquie', 'code' => 'TUR'],
            ['name' => 'Géorgie', 'code' => 'GEO'],
            ['name' => 'Arménie', 'code' => 'ARM'],
            ['name' => 'Azerbaïdjan', 'code' => 'AZE'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
